# Generated by Django 5.2 on 2025-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asl", "0004_aslvideohistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="aslvideohistory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aslvideohistory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
