# Generated by Django 5.2 on 2025-04-14 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
