# Generated by Django 5.2 on 2025-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_email_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_images/user.png", upload_to="profile_images/"
            ),
        ),
    ]
